# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rlm',
                'doc_host': 'https://numb3r33.github.io',
                'git_url': 'https://github.com/numb3r33/rlm',
                'lib_path': 'rlm'},
  'syms': { 'rlm.benchmarks': { 'rlm.benchmarks.benchmark_rlm': ('benchmark.html#benchmark_rlm', 'rlm/benchmarks.py'),
                                'rlm.benchmarks.benchmark_vanilla': ('benchmark.html#benchmark_vanilla', 'rlm/benchmarks.py')},
            'rlm.core': {'rlm.core.advanced_toolloop': ('core.html#advanced_toolloop', 'rlm/core.py')},
            'rlm.prompts': {},
            'rlm.tools': { 'rlm.tools.make_run_repl': ('tools.html#make_run_repl', 'rlm/tools.py'),
                           'rlm.tools.prep_shell': ('tools.html#prep_shell', 'rlm/tools.py')}}}
